os: linux
dist: bionic
language: generic

env:
  jobs:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp
    - LISP=ecl
    - LISP=abcl
    - LISP=allegro

jobs:
  allow_failures:
    - env: LISP=allegro
    - env: LISP=clisp

install:
  # Install cl-travis
  - curl -L https://raw.githubusercontent.com/sionescu/cl-travis/master/install.sh | bash

script:
  - cl -l nibbles -l nibbles-tests
       -e '(setf *debugger-hook*
                 (lambda (&rest ignorable)
                   (declare (ignore ignorable))
                   (uiop:quit -1)))'
       -e '(rt:do-tests)'
